Repository redhat-developer/vscode-java, pull requests merged in 2018-05, with the labels that each got.

#524 Updates find-java-home dependency
  package-lock.json
  package.json
Labels: build/infra, enhancement

#530 Add on-type formatting
  package.json
Labels: enhancement, formatter

#529 Update vscode-language-client and vscode
  package-lock.json
  package.json
Labels: build/infra, enhancement

#538 move class & interface snippets to server side
  snippets/java.json
Labels: content-assist, debt
