Repository redhat-developer/vscode-java, pull requests merged in 2020-08, with the labels that each got.

#1576 Fixed some vulnerable dependencies
  package-lock.json
  package.json
Labels: build/infra, dependencies

#1574 Add test case for rename file
  .vscode/launch.json
  .vscode/tasks.json
  gulpfile.js
  test/common.ts
  test/lightweight-mode-suite/publicApi.test.ts
  test/runtest.ts
  test/standard-mode-suite/publicApi.test.ts
  test/standard-mode-suite/rename.test.ts
Labels: debt

#1603 Remove mention of java.requirements.JDK11Warning from README
  README.md
Labels: documentation

#1602 Show a more detailed message about Java 11 requirement
  package.json
  src/requirements.ts
Labels: enhancement

#1599 Punctuation fix in import message
  src/extension.ts
Labels: typo
