Repository redhat-developer/vscode-java, pull requests merged in 2020-06, with the labels that each got.

#1487 Ignore /node_modules/ when webpack is watching sources
  webpack.config.js
Labels: build/infra, enhancement

#1503 support to resolve additional text edits
  src/extension.ts
Labels: content-assist, enhancement, performance

#1505 Register the semantic token provider after standard server is ready
  src/extension.ts
  src/standardLanguageClient.ts
Labels: enhancement
