Repository redhat-developer/vscode-java, pull requests merged in 2022-05, with the labels that each got.

#2371 Support publishing pre-release versions
  Jenkinsfile
  gulpfile.js
Labels: build/infra

#2459 Show field type when generating accessors
  src/protocol.ts
  src/sourceAction.ts
Labels: has conflicts

#2472 VS Code doesn't call shutdown when exiting the standard client
  src/extension.ts
  src/standardLanguageClient.ts
  src/syntaxLanguageClient.ts
Labels: in progress

#2484 added completion support for multiline comment blocks
  language-configuration.json
  src/extension.ts
Labels: typing
