Repository redhat-developer/vscode-java, pull requests merged in 2022-11, with the labels that each got.

#2790 set null analysis `interactive` by default
  README.md
  package.json
Labels: has conflicts

#2803 Add setting for string concatenations to text block conversion
  document/_java.learnMoreAboutCleanUps.md
  package.json
Labels: enhancement

#2796 Correct outdated descriptions `java.compile.nullAnalysis.enabled`
  README.md
  package.json
Labels: documentation

#2813 Add setting for invert equals calls on null
  document/_java.learnMoreAboutCleanUps.md
  package.json
Labels: enhancement

#2793 Support Gradle annotation processing
  README.md
  package.json
Labels: enhancement, Gradle, annotation-processing
