Repository redhat-developer/vscode-java, pull requests merged in 2022-06, with the labels that each got.

#2512 Verify that java.jdt.ls.java.home meets minimum JRE requirement.
  src/requirements.ts
Labels: bug

#2375 Add commands to view Java Language Server debug and error logs
  package.json
  package.nls.json
  package.nls.zh.json
  src/commands.ts
  src/extension.ts
  test/lightweight-mode-suite/extension.test.ts
  test/standard-mode-suite/extension.test.ts
Labels: bug

#2521 Add DCO documentation
  CONTRIBUTING.md
  DCO
Labels: documentation

#2522 Fix issues from the merging of the "Open All Log Files" command.
  package.json
  package.nls.json
  package.nls.zh.json
Labels: bug

#2526 Allow rebuild selected projects
  README.md
  package.json
  package.nls.json
  package.nls.zh.json
  src/commands.ts
  src/protocol.ts
  src/standardLanguageClient.ts
Labels: enhancement
