Repository redhat-developer/vscode-java, pull requests merged in 2022-02, with the labels that each got.

#2308 Update to Mocha 9.2.0
  package-lock.json
  package.json
Labels: dependencies

#2322 Fix typo in npm-install condition for ovsx installation.
  Jenkinsfile
Labels: build/infra

#2323 Fix issue #2319: Open Java extension log doesn't open latest file
  src/extension.ts
Labels: bug

#2320 Autoclose multiline strings (JEP 368)
  language-configuration.json
  src/extension.ts
  src/settings.ts
Labels: in progress
