Repository redhat-developer/vscode-java, pull requests merged in 2022-08, with the labels that each got.

#2608 Fix the activation events regression
  package.json
  src/gradle/gradleCodeActionProvider.ts
  src/pom/pomCodeActionProvider.ts
  test/standard-mode-suite/codeActionProvider.test.ts
  test/standard-mode-suite/extension.test.ts
Labels: bug

#2601 update deps: jdk-utils@0.4.4
  package-lock.json
  package.json
Labels: dependencies

#2612 Use plural form for reload projects command title
  README.md
  document/_java.notCoveredExecution.md
  package.nls.json
Labels: documentation

#2614 Support "Sort Members" Code Action
  README.md
  package.json
Labels: has conflicts
