Repository redhat-developer/vscode-java, pull requests merged in 2022-09, with the labels that each got.

#2415 Migrate from tslint to eslint
  .eslintrc.json
  .github/workflows/pr-verify.yml
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  .vscodeignore
  gulpfile.js
  package-lock.json
  package.json
  src/apiManager.ts
  src/documentSymbols.ts
  src/extension.api.ts
  src/extension.ts
  src/fileEventHandler.ts
  src/goToDefinition.ts
  src/gradle/gradleCodeActionProvider.ts
  src/hoverAction.ts
  src/inlayHintsProvider.ts
  src/javaServerStarter.ts
  src/languageStatusItemFactory.ts
  src/lombokSupport.ts
  src/pom/pomCodeActionProvider.ts
  src/protocol.ts
  src/providerDispatcher.ts
  src/recommendation/handlerImpl.ts
  src/requirements.ts
  src/serverStatus.ts
  src/serverStatusBarProvider.ts
  src/serverTaskPresenter.ts
  src/settings.ts
  src/sourceAction.ts
  src/standardLanguageClient.ts
  src/syntaxLanguageClient.ts
  src/typeHierarchy/model.ts
  src/typeHierarchy/protocol.ts
  src/typeHierarchy/references-view.d.ts
  src/typeHierarchy/typeHierarchyTree.ts
  src/typeHierarchy/util.ts
  test/lightweight-mode-suite/extension.test.ts
  test/lightweight-mode-suite/index.ts
  test/lightweight-mode-suite/publicApi.test.ts
  test/runtest.ts
  test/standard-mode-suite/extension.test.ts
  test/standard-mode-suite/gotoSuperImplementation.test.ts
  test/standard-mode-suite/index.ts
  test/standard-mode-suite/projects.test.ts
  test/standard-mode-suite/publicApi.test.ts
  test/standard-mode-suite/rename.test.ts
  test/standard-mode-suite/snippetCompletionProvider.test.ts
  test/standard-mode-suite/utils.test.ts
  tsconfig.json
  tslint.json
  webpack.config.js
Labels: build/infra

#2688 Fix the package statement missing when creating java files
  src/fileEventHandler.ts
Labels: bug, regression

#2704 Fix bad .git resourceFilter
  README.md
  package.json
Labels: bug
