Repository redhat-developer/vscode-java, pull requests merged in 2023-02, with the labels that each got.

#2915 Clarify the README quick start instructions.
  README.md
Labels: documentation

#2927 Add Github action to detect potential duplicate issues
  .github/workflows/duplicate-issues-detector.yaml
Labels: build/infra

#2377 Update language-client to 8.1.0
  package-lock.json
  package.json
  src/clientErrorHandler.ts
  src/extension.ts
  src/fileEventHandler.ts
  src/pasteEventHandler.ts
  src/refactorAction.ts
  src/sourceAction.ts
  src/standardLanguageClient.ts
  src/standardLanguageClientUtils.ts
  src/syntaxLanguageClient.ts
Labels: dependencies
