Repository redhat-developer/vscode-java, pull requests merged in 2023-06, with the labels that each got.

#3140 Use choice syntax as placeholder for method/field snippets.
  snippets/java.json
Labels: snippets

#3142 Set the default value of 'java.completion.matchCase' to 'firstLetter'
  README.md
  package.json
  src/utils.ts
Labels: content-assist

#3152 JDT_LS_PATH env var to reference local JDT-LS build
  CONTRIBUTING.md
  src/javaServerStarter.ts
Labels: build/infra

#3143 Support 'off' mode when fill the argument during completion
  README.md
  package.json
  src/utils.ts
Labels: content-assist
