Repository redhat-developer/vscode-java, pull requests merged in 2023-12, with the labels that each got.

#3406 Migrate Jenkins release job to GitHub Actions.
  .github/workflows/release.yml
Labels: build/infra

#3407 Improved grammar for kotlin based on official documentation
  language-support/kotlin/kotlin.tmLanguage.json
Labels: enhancement

#3413 Fix the typo: blob -> glob
  src/extension.ts
Labels: typing

#3421 Remove the compatibility check for createLanguageStatusItem() api
  src/extension.ts
  src/languageStatusItemFactory.ts
  src/lombokSupport.ts
  src/runtimeStatusBarProvider.ts
Labels: debt

#3428 Remember the choice when asking project selection
  package-lock.json
  package.json
  src/buildFilesSelector.ts
  src/settings.ts
Labels: bug

#3439 Reduce delegate command calls when classpath changes
  src/lombokSupport.ts
  src/standardLanguageClient.ts
Labels: performance
