Repository redhat-developer/vscode-java, pull requests merged in 2023-04, with the labels that each got.

#3042 Add telemetry for extension recommendations
  USAGE_DATA.md
  src/recommendation/handlerImpl.ts
Labels: telemetry

#3052 Remove the workaround to show the refactoring document
  package-lock.json
  package.json
  src/codeActionProvider.ts
Labels: debt

#3070 Remove 'resolveAdditionalTextEditsSupport' from extended client capabilities
  src/extension.ts
Labels: debt

#3082 Ensure meaningful information is displayed via progress reporter
  src/serverTaskPresenter.ts
Labels: bug

#2586 Added restart java language server command
  README.md
  package.json
  package.nls.json
  src/commands.ts
  src/extension.ts
  src/javaServerStarter.ts
  src/standardLanguageClient.ts
  src/syntaxLanguageClient.ts
  test/lightweight-mode-suite/extension.test.ts
  test/standard-mode-suite/extension.test.ts
Labels: enhancement, upstream
