Repository redhat-developer/vscode-java, pull requests merged in 2023-01, with the labels that each got.

#2847 Fix Build Status badge
  README.md
Labels: documentation

#2854 Work around vsce refusal to publish extensions with proposed API
  package.json
Labels: build/infra

#2879 React to vsce renaming to @vscode/vsce.
  Jenkinsfile
Labels: build/infra

#2891 Add setting for try-with-resource clean up
  document/_java.learnMoreAboutCleanUps.md
  package.json
Labels: enhancement

#2895 Use commit SHA instead of branch name for third-party actions
  .github/workflows/conflictDetector.yaml
Labels: build/infra
