Repository redhat-developer/vscode-java, pull requests merged in 2024-01, with the labels that each got.

#3402 Automatically track JDK of eclipse.jdt.ls
  .github/scripts/check_and_update_jdk.py
  .github/workflows/bump-jdk.yml
Labels: build/infra

#3463 Use `source.gradle-kotlin-dsl` instead of `source.kotlin` to avoid clashes with other Kotlin grammars
  language-support/kotlin/kotlin.tmLanguage.json
  package.json
Labels: Gradle, highlighting, kotlin

#3465 Inject html syntax highlighting via language=html comment
  language-support/html/inline-html.json
  package.json
Labels: enhancement, highlighting

#2928 Enable no-response bot to auto close inactive issues
  .github/workflows/no-response.yml
Labels: build/infra
