Repository redhat-developer/vscode-java, pull requests merged in 2024-10, with the labels that each got.

#3809 Use Node 20 in release-job only.
  .github/workflows/release.yml
Labels: build/infra

#3558 Enable javac-based compilation
  .github/workflows/release.yml
  README.md
  USAGE_DATA.md
  package.json
  src/extension.ts
  src/javaServerStarter.ts
  src/requirements.ts
  src/settings.ts
  src/utils.ts
Labels: enhancement

#3833 Update embedded lombok library name to reflect actual version.
  gulpfile.js
Labels: Lombok
